---
ansible_connection: ssh

ansible_user: ansiuser
ansible_password: "{{ vault_lab_ansiuser_password }}"

ansible_python_interpreter: /usr/bin/python3

sql_repo_url: https://packages.microsoft.com/config/ubuntu/24.04/mssql-server-2025.list

sql_tools_repo_url: https://packages.microsoft.com/config/ubuntu/24.04/prod.list
