---
ansible_connection: winrm
ansible_port: 5985

ansible_winrm_transport: ntlm

ansible_winrm_scheme: http

ansible_user: 'DATASAT\ansiuser'

ansible_password: "{{ vault_lab_ansiuser_password }}"

sql_instance: localhost
